//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyAgility_API.Models.myagility
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lap
    {
        public int ID { get; set; }
        public Nullable<int> CompetitionID { get; set; }
        public string Type { get; set; }
        public System.TimeSpan LapStartTime { get; set; }
        public int LapLength { get; set; }
        public System.TimeSpan ReferenceTime { get; set; }
        public System.TimeSpan ActualTime { get; set; }
        public int MeterPerSecond { get; set; }
        public int NumbersOfFails { get; set; }
        public string Comments { get; set; }
    
        public virtual Competition Competition { get; set; }
    }
}
